crafting-recipe:
- 266,331,266
- 331,264,331
- 266,331,266
allow-crafting: true
allow-command-insertion: true
permissions:
    example:
    - enchant @p
    - weather clear
    - say
    - time
voxelsniper-blacklist:
- punish
- painting
- jockey
- comet
- copypasta
- warp
- voltmeter
listen-for-redstone: true
disable-filtering:
    plugins:
    - example
    commands:
    - example
commands:
    eject:
        enabled: true
        aliases:
        - ej
    kill:
        enabled: true
        aliases:
    accelerate:
        enabled: true
        aliases:
        - acc
    delay:
        enabled: true
        aliases:
    redstone:
        enabled: true
        aliases:
        - rs
    explode:
        enabled: true
        aliases:
    equip:
        enabled: true
        aliases:
    repeat:
        enabled: true
        aliases:
        - re
        - rp
    setflag:
        enabled: true
        aliases:
        - sf
    setglobalflag:
        enabled: true
        aliases:
        - sgf
    inventory:
        enabled: true
        aliases:
        - inv
    voxelsniper:
        enabled: true
        aliases:
        - vs
    teleport:
        enabled: true
        aliases:
        - tp
    safeteleport:
        enabled: true
        aliases:
        - safetp
    spawn:
        enabled: true
        aliases:
    message:
        enabled: true
        aliases:
        - msg
    rawmessage:
        enabled: true
        aliases:
        - rawmsg
    setdata:
        enabled: true
        aliases:
